### ISSUE TITLE
Make the component isomorphic

### ISSUE THREAD

**Issue by zdila** [nihey/react-clipboard.js#25]
Please make the component isomorphic. Now it can't be used for serverside rendering because it uses things like Element.

**Comment by zdila** [comment]
Solution is to import `clipboard` in `componentDidMount` like this:
```javascript
const Clipboard = require('clipboard');
this.clipboard = new Clipboard(this.refs.element, options);
```

**Comment by nihey** [comment]
Thanks for the idea

I'm not really familiar with React's server rendered components. But from what I've understood, it breaks because `clipboard` is imported on the outermost scope, causing the server, that does not have `window.Element` to break, right?

Seems like a simple change. Would you be willing to contribute? I can merge it and publish it as soon as I get home.

**Comment by nihey** [comment]
Thanks for the contribution @zdila 

The latest release (0.2.4) should have this issue fixed.

**Comment by zdila** [comment]
I ma sorry but this was not enough. I had to also change `libraryTarget` to `commonjs2`. I've never build library so I was not aware of this. Will send another pull request.
