### ISSUE TITLE
I don't get the functionality

### ISSUE THREAD

**Issue by hobri** [nihey/react-clipboard.js#65]
Forgive me if I'm missing something here, but based on the examples, you're not actually copying the element -- you're copying some text defined in a JavaScript object, correct? I think it's misleading to name this after clipboard.js, as one of the features of that was the ability to copy the content of actual DOM elements (including HTML that didn't need to be escaped). It supported rich-text copying as well (equivalent to ctrl+a, ctrl+c on a webpage)

Is there an example of this usage, or is this supported?

Thanks for hearing me out as I continue to look for a solution.

**Comment by nihey** [comment]
@hobri This component is named after [clipboard.js](https://clipboardjs.com/) because it wraps all of its features inside a React component, even copying content of other DOM elements (even the ones that were not build using React).

For instance, you could copy the content of a element with `foo` id anywhere in your DOM by using:

```javascript
// Untested
function MyButton() {
  return (
    <Clipboard data-clipboard-target="#foo">
      copy content of #foo to clipboard
    </Clipboard>
  );
}
```

I can also build some more examples and insert them on the `README.md` file later.
